apiVersion: v1
kind: Service
metadata:
  name: dind-service
  namespace: docker-in-docker
spec:
  selector:
    workload: deployment-docker-in-docker-dind
  ports:
    - name: dind
      port: 2376
      targetPort: 2376
      protocol: TCP
  type: NodePort