namespace: github

images:
- name: github-runner

resources:
- deployment.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- envs:
  - ./.env
  name: github-secret
  type: Opaque
